name: Triggered by a change
on: [push]

jobs:
  triggered-by-a-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: export_paths
        run: |
          PATHS="^a/\|"
          PATHS+="^aa/\|"
          PATHS+="^aaa/target.txt$"
          echo "::set-output name=paths::${PATHS}"
      - run: |
          echo ${{ steps.export_paths.outputs.PATHS }}
      - id: skip_flag
        run: |
          if [[ ${{ github.sha }} != $(git rev-parse origin/main) ]] \
          && [[ 0 == $(( $(git diff origin/main...${{ github.sha }} --name-only | grep '${{ steps.export_paths.outputs.paths }}' | wc -l) )) ]]
          then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

      - if: steps.skip_flag.outputs.skip == "true"
        run: echo "Skip!"

      - if: steps.skip_flag.outputs.skip != "true"
        run: echo "Executed!"
