name: Triggered by a change
on: [push]

env:
  PATHS: '^a/\|^aa/\|^aaa/'
jobs:
  triggered-by-a-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo ${{ join(env.PATHS, '\|') }}
      - run: |
          if [[ ${{ github.sha }} != $(git rev-parse origin/main) ]] \
          && [[ 0 == $(( $(git diff origin/main...${{ github.sha }} --name-only | grep ${{ env.PATHS }} | wc -l) )) ]]
          then
            echo "Skip"
          else
            echo "a changed!"
          fi
