name: Triggered by b change
on: [push]
jobs:
  triggered-by-b-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git branch
      - run: git branch -a
      - run: git rev-parse origin/main
      - run: |
          if [[ ${{ github.sha }} != $(git rev-parse origin/main) ]] \
          && [[ 0 == $(( $(git diff origin/main...${{ github.sha }} --name-only | grep '^b/' | wc -l) )) ]]
          then
            echo "Skip"
          else
            echo "b changed!"
          fi
