name: Triggered by b change
on: [push]

jobs:
  triggered-by-b-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: export_paths
        run: |
          PATHS="^b/"
          echo "::set-output name=paths::${PATHS}"
      - run: |
          echo ${{ steps.export_paths.outputs.PATHS }}
      - run: |
          if [[ ${{ github.sha }} != $(git rev-parse origin/main) ]] \
          && [[ 0 == $(( $(git diff origin/main...${{ github.sha }} --name-only | grep '${{ steps.export_paths.outputs.PATHS }}' | wc -l) )) ]]
          then
            echo "Skip"
          else
            echo "b changed!"
          fi
