name: Triggered by b change
on: [push]
jobs:
  triggered-by-b-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ${{ github.sha }} != $(git rev-parse origin/main) ]] \
          && [[ 0 == $(( $(git diff origin/main...${{ github.sha }} --name-only | grep '^b/') | wc -l )) ]]
          then
            echo "Skip"
          else
            echo "b changed!"
          fi
