name: Sample Workflow
on: [push]
jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'de')
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - run: echo success
