name: Sample Workflow
on: [push]
jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github }}
      - run: echo success
